# Disable Jekyll processing
plugins: []
markdown: kramdown
highlighter: rouge
safe: true
lsi: false
future: false
show_drafts: false
limit_posts: 0
pygments: false
relative_permalinks: false
exclude: [node_modules, frontend/node_modules, backend/node_modules, .git, .github] 